### ISSUE TITLE
Blank page at menu 'TEAMS' and 'GAME LOGS'

### ISSUE THREAD

**Issue by assazzin** [facebook/fbctf#158]
Platform is very well but I found some issue while I remove some quiz.
There is step by step that issue was happened.

1. Add a quiz.
2. Play a game and correct the answer of previous quiz.   (menu "TEAMS" and "GAME LOGS" can open)
3. Remove all quiz, now menu "TEAMS" and "GAME LOGS" can not access (got a blank page)

There are some error from /var/log/hhvm/error.log

`[Sun Jul  3 12:26:14 2016] [hphp] [926:7f46b4fff700:208:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected exactly one result' in /var/www/fbctf/src/models/Level.php:613\nStack trace:\n#0 /var/www/fbctf/src/models/Level.php(613): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/AdminController.php(2116): Level::gen()\n#2 /var/www/fbctf/src/controllers/AdminController.php(2262): AdminController->genRenderLogsContent()\n#3 /var/www/fbctf/src/controllers/AdminController.php(2272): AdminController->genRenderPage()\n#4 /var/www/fbctf/src/controllers/Controller.php(12): AdminController->genRenderBody()\n#5 /var/www/fbctf/src/Router.php(72): Controller->genRender()\n#6 /var/www/fbctf/src/Router.php(18): Router::genRouteNormal()\n#7 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#8 (): genInit()\n#9 (): HH\\WaitHandle->join()\n#10 /var/www/fbctf/src/index.php(19): HH\\Asio\\join()\n#11 {main}`

`[Sun Jul  3 12:26:20 2016] [hphp] [926:7f46b4fff700:211:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected exactly one result' in /var/www/fbctf/src/models/Level.php:613\nStack trace:\n#0 /var/www/fbctf/src/models/Level.php(613): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/AdminController.php(2116): Level::gen()\n#2 /var/www/fbctf/src/controllers/AdminController.php(2262): AdminController->genRenderLogsContent()\n#3 /var/www/fbctf/src/controllers/AdminController.php(2272): AdminController->genRenderPage()\n#4 /var/www/fbctf/src/controllers/Controller.php(12): AdminController->genRenderBody()\n#5 /var/www/fbctf/src/Router.php(72): Controller->genRender()\n#6 /var/www/fbctf/src/Router.php(18): Router::genRouteNormal()\n#7 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#8 (): genInit()\n#9 (): HH\\WaitHandle->join()\n#10 /var/www/fbctf/src/index.php(19): HH\\Asio\\join()\n#11 {main}`

Thank you :)

**Comment by assazzin** [comment]
I found detour fix this issue by deal with reset all score.

> 'END GAME' and re 'BEGIN GAME'

so I keep in mind I will not delete quiz while game is running.
