### ISSUE TITLE
Test fails during install on AWS, but then it works

### ISSUE THREAD

**Issue by markszabo** [facebook/fbctf#211]
I freshly created an EC2 instance on AWS using Ubuntu Server 14.04 (64 bit) on a t2.micro (Variable ECUs, 1 vCPUs, 2.5 GHz, Intel Xeon Family, 1 GiB memory, EBS only). Then installed fbctf using these commands from the readme:
```
sudo apt-get update
sudo apt-get install git
git clone https://github.com/facebook/fbctf
cd fbctf
./extra/provision.sh -m prod -c self -s $PWD
```
(I have chosen self signed cert, because Let's encrypt won't generate a certificate for *.compute-X.amazonaws.com type of domains.)

Installations goes well, but I got one error in the middle:
```
npm http GET https://registry.npmjs.org/flow-bin/-/flow-bin-0.32.0.tgz
npm http 200 https://registry.npmjs.org/flow-bin/-/flow-bin-0.32.0.tgz
/usr/local/bin/flow -> /usr/local/lib/node_modules/flow-bin/cli.js
flow-bin@0.32.0 /usr/local/lib/node_modules/flow-bin
Running "force:eslint" (force) task

Running "force-internal:pre:eslint" (force-internal) task
>> Enable force mode for task eslint.

Running "eslint:dist" (eslint) task

/var/www/fbctf/src/static/js/plugins.js
  51:9  error  Move function declaration to function body root  no-inner-declarations

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:dist" failed. Used --force, continuing.

Running "force-internal:post:eslint" (force-internal) task
>> Reset force mode for task eslint.

Running "run:flow" (run) task
flow is still initializing; this can take some time. [processing] -Launching Flow server for /var/www/fbctf/src
Spawned flow server (pid=8510)
Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
Started a new flow server: \flow is still initializing; this can take some time. [processing] |No errors!
```
Then right after it finishes with the installation, I got an other error:
```
[+] Creating user...
[+] DB Connection file
[+] Adding default admin user
[+] The password for admin is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[+] Enabling HHVM RepoAuthoritative mode
running hphp...
parsing inputs...
Unable to stat file /var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test1.php
Unable to stat file /var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test2.php
Unable to stat file /var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test3.php
Unable to stat file /var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test4.php
Unable to stat file /var/www/fbctf/vendor/phpunit/php-token-stream/vendor/autoload.php
Unable to stat file /var/www/fbctf/vendor/phpunit/phpunit-mock-objects/vendor/autoload.php
Unable to stat file /var/www/fbctf/vendor/phpunit/phpunit/build/tools/phar:/composer.phar/bin/composer
Unable to stat file /var/www/fbctf/vendor/phpunit/phpunit/vendor/autoload.php
Unable to stat file /var/www/fbctf/vendor/sebastian/comparator/vendor/autoload.php
Unable to stat file /var/www/fbctf/vendor/sebastian/resource-operations/build/arginfo.php
analyzeProgram...
analyzeProgram took 0'00" (621564 us) wall time
parsing inputs took 0'25" (25511737 us) wall time
pre-optimizing...

Assertion failure: /tmp/tmp.3f6VuVMO0N/hphp/runtime/base/rds.cpp:534: void HPHP::rds::threadInit(): assertion `tl_base != ((void *) -1)' failed.
Failed to mmap persistent RDS region. errno = Cannot allocate memory

Core dumped: Aborted
Stack trace in /tmp/stacktrace.9008.log
hphp failed
running hphp took 0'28" (28252271 us) wall time
ubuntu@ip-172-xx-xx-xxx:~/fbctf$ 
``` 
Also the website gives 502 error. But when I restart the server, it seems to work.

Is this because of the memory limitation (only 1 GiB) of the t2.micro instance? I repeated the same process, and got the same error, so it seems to persist. Will it cause troubles in the future?

**Comment by gsingh93** [comment]
Yea, there was a similar issue a few weeks ago with this failing on a micro. We might have to not enable repo authoritative mode for test builds...

**Comment by javuto** [comment]
We can have some performance tweaks only to apply in production environments. Another good one to switch is enabling binlogs only in dev mode.

**Comment by markszabo** [comment]
Okay, since the system works and I just wanted to let you know about the issue, I'm closing this thread.

**Comment by markszabo** [comment]
Meanwhile I had to reinstall the thing, and it just kept getting this error while doing something with composer:
```
Fatal error: Uncaught exception 'ErrorException' with message 'fork failed - Cannot allocate memory' in phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:954
Stack trace:
#0 (): Composer\Util\ErrorHandler::handle()
#1 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(954): proc_open()
#2 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException()
#6 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run()
#7 phar://composer.phar/bin/composer(43): Composer\Console\Application->run()
#8 /var/www/fbctf/composer.phar(24): include()
#9 {main}
```
Based on [this SO thread](http://stackoverflow.com/a/24648506) the solution was:
```
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1
```
Then I rerun the provision script, and now it finished, and also the previous error disappeared.

**Comment by iFurySt** [comment]
i got the same error.

**Comment by iangcarroll** [comment]
@iFurySt You need more memory or more swap space.

**Comment by iFurySt** [comment]
@iangcarroll thx, you are right.1G is not enough.

**Comment by markszabo** [comment]
Let me share my process of the install on an AWS t2.micro:

First fix the locale error (based on https://ubuntuforums.org/showthread.php?t=1346581) - my own computer's locale is set to Hungarian, while the AWS machine to English, and this creates problems with ssh. So this step might not needed, and you need to replace `hu` with your local locale anyway.

```
sudo locale-gen en_US en_US.UTF-8 hu_HU hu_HU.UTF-8
sudo dpkg-reconfigure locales
```

Then add swap (based on http://stackoverflow.com/a/24648506)

```
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo /sbin/swapon /var/swap.1
```

Download fbctf (based on https://github.com/facebook/fbctf/)

```
sudo apt-get update
sudo apt-get install git
git clone https://github.com/facebook/fbctf
cd fbctf
```

Check the dns settings (it should resolve to it's own IP) - I set it up earlier with my DNS server, and the check here is just to make sure the DNS cache is updated. If you are not using Let's encrypt certs, you can skip this step.

```
nslookup whatever.mysite.com
```

Install fbctf

```
./extra/provision.sh -m prod -c certbot -D whatever.mysite.com -e whatever@mysite.com -s $PWD
```
