### ISSUE TITLE
Error: Cannot find module 'ansi-regex' when installing flow-bin

### ISSUE THREAD

**Issue by adrianbrink** [facebook/fbctf#224]
System:
Digital Ocean Droplet
14.04.05 Ubuntu

Created new user sammy.
Running the production deployment script without sudo.
Entering sudo password whenever prompted.

Command: `./extra/provision.sh -m prod -s $PWD`

Error msg:
```
npm http 304 https://registry.npmjs.org/flow-bin
/usr/local/bin/flow -> /usr/local/lib/node_modules/flow-bin/cli.js
flow-bin@0.32.0 /usr/local/lib/node_modules/flow-bin

module.js:340
    throw err;
          ^
Error: Cannot find module 'ansi-regex'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/fbctf/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/grunt-legacy-log-utils/node_modules/chalk/node_modules/strip-ansi/index.js:2:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/fbctf/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/fbctf/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/grunt-legacy-log-utils/node_modules/chalk/index.js:4:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/fbctf/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/fbctf/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/grunt-legacy-log-utils/index.js:12:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/fbctf/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/fbctf/node_modules/grunt/node_modules/grunt-legacy-log/index.js:25:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/fbctf/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/fbctf/node_modules/grunt/lib/grunt.js:21:11)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt/node_modules/grunt-cli/bin/grunt:44:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt/bin/grunt:3:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

**Comment by javuto** [comment]
Can you try again adding a ```sudo``` in ```provision.sh```, line 243? https://github.com/facebook/fbctf/blob/master/extra/provision.sh#L243

**Comment by iFurySt** [comment]
> adding a `sudo` in `provision.sh`, line 243

i got the same err.can someone help?

**Comment by javuto** [comment]
This should be fixed here: https://github.com/facebook/fbctf/pull/303

**Comment by iFurySt** [comment]
@javuto i found that problem is grunt.btw, thx
