### ISSUE TITLE
submit flag quickly leads to get score more than once

### ISSUE THREAD

**Issue by zjuchenyuan** [facebook/fbctf#334]
I submitted flag by clicking "SUBMIT" very quickly and repeatedly,
then I found out that in the ACTIVITY board, I get 4 log saying "[.. ago]admin captured China", besides, the score also added more than once. 
This means if a correct flag is submitted repeatedly in a short time, a player can get score more than he should.

I think this is a huge problem when this platform is used in formal competition.

eh...this may be caused by my modifications to ScoreLog.php,
because I get this in error.log:
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function contains() on a non-object (boolean)' in /var/www/fbctf/src/models/ScoreLog.php:107
Stack trace:
#0 /var/www/fbctf/src/static/svg/map/world.php(62): ScoreLog::genPreviousScore()
#1 /var/www/fbctf/src/static/svg/map/world.php(11): WorldMapController->genRenderWorldMap()
#2 (): WorldMapController->genRender()
#3 (): HH\\WaitHandle->join()
#4 /var/www/fbctf/src/static/svg/map/world.php(110): HH\\Asio\\join()
#5 {main}

So, to make the page not returning 500, I modifyed the /var/www/fbctf/src/models/ScoreLog.php:
Original:  if ($level_captures->contains($level_id)) {
After modification: if ($level_captures && $level_captures->contains($level_id)) {

Em...this maybe my fault to change it and caused such flag submit problem, 
but why I get this error log and the whole platform cannot work after I build by Docker

PM: in previous version I tried (docker qazbnm456/dockerized_fbctf), this flag multi-submit problem do exists, I don't know if the newest one fixed it

**Comment by zjuchenyuan** [comment]
I founded out that the memcached doesn't start automatically in docker,
So, the error.log is just caused by not connected to memcached...

I tried again and found out this problem doesn't appear again.

In conclusion, remember to "service memcached start"
