### ISSUE TITLE
How can I change default port fbctf with docker

### ISSUE THREAD

**Issue by Unaim1** [facebook/fbctf#694]
Hi, I installed fbctf in a Standard Docker Startup, and I have my ports 80 and 443 in use. So I want to change the working port to another. How can I do it? I get this error obviosly.

`Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint fbctf_nginx_1 (9f17d4a31c82d9d6ec6071ca582c825851d1368d6c355a441e0621f3c03915cb): Error starting userland proxy: listen tcp 0.0.0.0:443: listen: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 563, in execute_convergence_plan
  File "compose/service.py", line 490, in _execute_convergence_recreate
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 483, in recreate
  File "compose/service.py", line 602, in recreate_container
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[1197] Failed to execute script docker-compose`

**Comment by 0x000NULL** [comment]
docker run -d -p 80:81
